# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('from_hour', models.CharField(max_length=255)),
                ('to_hour', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('weekday', 'from_hour'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='hour',
            unique_together=set([('weekday', 'from_hour', 'to_hour')]),
        ),
    ]
