# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20170106_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Home page title', max_length=255)),
                ('message', models.TextField(help_text='Home page message')),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(help_text='About page description'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(help_text='About page title', max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(help_text='Contact page description'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(help_text='Contact page title', max_length=100),
        ),
    ]
