# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20170112_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hour',
            options={'ordering': ('weekday', 'from_hour'), 'verbose_name_plural': 'Hours'},
        ),
    ]
