# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_auto_20170112_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='message',
            field=models.TextField(blank=True, help_text='Home page message'),
        ),
    ]
