# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featured',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='art',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
