# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 01:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20170106_1546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Featured',
        ),
    ]
