# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_delete_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='art',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Art'},
        ),
        migrations.AlterModelOptions(
            name='bathroom',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Bathroom'},
        ),
        migrations.AlterModelOptions(
            name='bedroom',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Bedroom'},
        ),
        migrations.AlterModelOptions(
            name='dining',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Dining'},
        ),
        migrations.AlterModelOptions(
            name='hallway',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Hallway'},
        ),
        migrations.AlterModelOptions(
            name='living',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Living'},
        ),
        migrations.AlterModelOptions(
            name='musical',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Musical'},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Office'},
        ),
    ]
